// 补充数据：为每个节点追加更多内容，实现"大而全"学习地图

export const EXTRA_TOPICS: Record<string, { name: string; points: string[] }[]> = {
  'pm-thinking': [
    { name: 'AI PRD撰写规范', points: [
      'AI PRD结构：背景/目标/功能/指标/排期的标准结构 + AI特殊章节',
      '模型行为规范：定义AI在各类场景下的预期行为。正常case、边界case、异常case的处理规则',
      '效果指标定义：准确率/召回率/延迟/成本等AI特有指标的定义和目标值',
      '降级方案设计：AI不可用时的兜底方案。大模型→小模型→规则→人工的分层降级',
      '测试用例设计：AI产品的测试用例设计。Happy path、Bad case、对抗测试',
      '上线 Checklist：AI产品上线的检查清单。模型版本、效果验证、降级测试、监控告警',
    ] },
    { name: '产品沟通与表达', points: [
      'PRD写作：从背景/目标/功能/指标/排期的标准结构，到AI PRD的特殊章节',
      '产品评审：如何组织高效的需求评审，控制时间、聚焦决策点',
      '向上沟通：向老板讲清楚产品价值，用数据说话、用故事打动',
      '跨部门协作：和工程/设计/运营/销售的沟通策略和协作框架',
      '用户沟通：如何做用户访谈、收集反馈、管理用户预期',
      '产品发布会：从内部对齐到外部发布的完整沟通策略',
      '危机沟通：产品出问题时的沟通策略，透明、及时、有行动',
      '文档体系：PRD/技术方案/竞品分析/复盘报告的文档体系设计',
    ] },
    { name: '产品创新方法', points: [
      '设计思维：Empathize→Define→Ideate→Prototype→Test的完整流程',
      'TRIZ创新方法：40个发明原理在产品创新中的应用',
      'SCAMPER法：替代/合并/调整/修改/其他用途/消除/重组的创新思考',
      '逆向思维：从"如果反过来会怎样"出发的创新方法',
      '跨界借鉴：从其他行业借鉴产品方案，如航空业→医疗业的安全清单',
      '用户共创：让用户参与产品创新的方法和工具',
      '内部创新：在大型组织中推动创新的方法，20%时间/黑客松/创新实验室',
      'AI驱动的创新：用AI发现用户需求、生成方案、加速验证的新范式',
    ] },
    { name: '产品复盘与迭代', points: [
      '复盘框架：目标回顾→结果对比→原因分析→经验总结→行动计划',
      '数据复盘：用数据验证产品决策的对错，而非事后找理由',
      '用户复盘：从用户反馈中发现产品问题的模式',
      '技术复盘：技术选型/架构决策的复盘，避免重复犯错',
      '竞品复盘：分析竞品动作背后的逻辑，而非简单模仿',
      '迭代规划：基于复盘结论制定下一轮迭代计划',
      '知识沉淀：把复盘结论转化为团队知识，避免"重复踩坑"',
      '复盘文化：建立"不指责、只改进"的复盘文化',
    ] },
  ],
  'user-research': [
    { name: '用户行为分析', points: [
      '点击流分析：用户在页面上的点击路径和停留时间分析',
      '热力图分析：页面区域的点击/滚动/注意力热力图',
      '会话回放：用户操作的全过程录制和回放分析',
      '漏斗转化分析：每一步的转化率和流失原因',
      '用户分群：基于行为的用户聚类和画像构建',
      '归因分析：用户行为和业务结果的因果关系',
      '行为预测：基于历史行为预测用户下一步操作',
      '异常行为检测：识别异常用户行为，发现产品问题或作弊',
    ] },
    { name: '可用性测试进阶', points: [
      '远程可用性测试：工具选择、任务设计、结果分析方法',
      '无主持测试：用户自主完成测试任务，降低成本扩大样本',
      'A/B测试+可用性：定量和定性结合的测试方法',
      '眼动追踪：用户注意力分布的客观测量方法',
      '卡片排序进阶：开放/封闭/混合排序的适用场景',
      '树形测试：信息架构的验证方法，和卡片排序互补',
      '第一点击测试：验证用户能否找到关键入口',
      '可用性基准：建立产品的可用性基准线，追踪改进',
    ] },
    { name: '研究伦理与合规', points: [
      '知情同意：用户研究中的知情同意原则和实操',
      '数据保护：GDPR/CCPA对用户研究数据的要求',
      '隐私保护：用户数据的脱敏、匿名化处理方法',
      '弱势群体保护：儿童/老年人/残障人士的研究特殊考量',
      'AI研究伦理：用AI做研究时的特殊伦理问题',
      '研究数据管理：研究数据的存储、访问、销毁策略',
      '研究透明度：向用户披露研究目的和结果的方法',
      '伦理审查：什么时候需要伦理审查，如何进行',
    ] },
  ],
  'product-design': [
    { name: 'AI产品原型设计', points: [
      'Wizard of Oz原型：用人工模拟AI，快速验证体验假设',
      '对话流设计：对话式产品的流程图和状态机设计',
      'AI输出模拟：用预设回复模拟AI输出，测试交互方案',
      'Figma AI插件：用AI辅助设计，加速原型制作',
      '交互规范文档：AI产品的交互规范定义和文档化',
      '多状态设计：AI不同状态（加载/成功/部分成功/失败）的界面设计',
      '渐进式体验设计：从简单到复杂的AI能力展示设计',
      '响应式AI设计：不同设备/网络条件下的AI体验适配',
    ] },
    { name: 'AI产品无障碍设计', points: [
      'WCAG标准：Web内容无障碍指南在AI产品中的应用',
      '屏幕阅读器适配：AI输出如何被屏幕阅读器正确读取',
      '语音交互无障碍：语音AI对听障/语障用户的支持',
      '认知无障碍：简化AI产品的认知负荷，降低使用门槛',
      'AI辅助无障碍：用AI增强产品的无障碍能力',
      '色盲友好设计：AI可视化产品的色盲友好配色',
      '键盘导航：AI产品的完整键盘导航支持',
      '无障碍测试：自动化和人工无障碍测试方法',
    ] },
    { name: 'AI产品国际化设计', points: [
      '多语言设计：AI产品多语言支持的交互设计挑战',
      '文化适配：不同文化背景下AI产品的交互差异',
      '本地化策略：AI产品的本地化不只是翻译，还有模型和内容适配',
      '时区处理：全球化AI产品的时间显示和调度设计',
      '货币和单位：不同地区的货币/度量衡/日期格式适配',
      '合规差异：不同国家AI监管对产品设计的影响',
      '输入法适配：不同语言输入法对AI交互的影响',
      'AI偏见本地化：不同地区对AI偏见的敏感度差异',
    ] },
  ],
  'pm-capability': [
    { name: 'AI PM软技能与职业素养', points: [
      '跨团队协作（253个JD中57次提及）：AI产品天然跨团队（算法+工程+产品+业务），协作是生存技能。建立定期对齐机制、用数据说话、明确责任边界',
      '沟通表达（38次提及）：在技术团队和业务团队之间做翻译。把技术风险翻译成业务语言、把业务需求翻译成技术规范',
      '项目管理（24次提及）：AI项目不确定性高，需要强项目管理。敏捷迭代、风险预案、里程碑管理',
      '逻辑思维（18次提及）：AI系统复杂度高，逻辑不清会迷失。结构化思考、MECE原则、因果推理',
      '自驱力（15次提及）：AI领域没有成熟方法论可抄，需要自己探索。主动学习、主动复盘、主动推动',
      '抗压能力（14次提及）：模型效果不稳定、上线后可能翻车，压力是常态。情绪管理、问题拆解、寻求支持',
      '快速学习（12次提及）：AI领域变化极快，3个月前的认知可能已过时。建立学习习惯、关注关键信源、实践验证',
      '结果导向（8次提及）：AI产品容易陷入技术自嗨，必须聚焦业务结果。定义成功指标、追踪业务影响、用数据证伪',
      '创新精神（8次提及）：AI是新领域，需要突破传统产品思维。实验文化、快速验证、容忍失败',
    ] },
    { name: 'AI PM职业路径', points: [
      '初级AI PM（0-2年）：执行为主，学会写AI PRD、做评估、跟项目',
      '中级AI PM（2-5年）：独立负责AI产品，能做技术选型和架构决策',
      '高级AI PM（5-8年）：定义AI产品方向，带团队，做战略决策',
      'AI产品总监（8年+）：管理产品线，制定AI战略，影响行业',
      '技术型AI PM：偏技术理解，和算法团队深度协作',
      '业务型AI PM：偏业务洞察，找到AI落地的最佳场景',
      '创业型AI PM：从0到1做AI产品，需要全栈能力',
      '转型路径：传统PM→AI PM的6个月转型计划',
    ] },
    { name: 'AI PM日常工具链', points: [
      '项目管理：Jira/Linear/Asana，AI项目的特殊管理需求',
      '文档协作：Notion/飞书/Confluence，AI PRD模板和知识库',
      '设计协作：Figma/FigJam，AI产品的设计规范和组件库',
      '数据分析：Amplitude/Mixpanel/SQL，AI产品的数据监控',
      'AI开发：OpenAI Playground/Anthropic Console，Prompt调试',
      'AI评估：Promptfoo/LangSmith，AI效果的自动化评估',
      '沟通协作：Slack/飞书/Zoom，异步沟通和知识共享',
      '个人效率：Copilot/ChatGPT/Claude，AI辅助日常工作',
    ] },
    { name: 'AI PM常见职业困惑', points: [
      '"我不懂代码能做AI PM吗？"——能，但需要理解技术原理和边界',
      '"AI PM和算法工程师的边界在哪？"——PM定义"做什么"，算法决定"怎么做"',
      '"传统PM经验在AI领域有用吗？"——有用，产品思维是通用的，但需要补充AI知识',
      '"AI PM会被AI替代吗？"——不会，但不会用AI的PM会被会用AI的PM替代',
      '"要不要去读AI相关的硕士？"——不是必须，实战经验>学历，但系统学习有帮助',
      '"大厂AI PM和创业公司AI PM怎么选？"——大厂学体系，创业学全栈，根据阶段选择',
      '"AI PM的薪资天花板在哪？"——高级AI PM薪资已超过传统PM，但需要持续学习',
      '"如何保持AI知识的更新？"——关注关键博客/论文/社区，每周至少3小时学习',
    ] },
  ],
  'ai-fundamentals': [
    { name: 'AI PM模型理解深度边界', points: [
      '第一层（所有PM必须）：LLM生成机制（自回归、Next Token Prediction）、Token与上下文窗口（物理限制、产品设计影响）、采样策略（temperature/top_p/top_k对体验的影响）、幻觉与可靠性（为什么幻觉、如何兜底）、能力边界（什么能做/不能做/做了不可靠）、成本结构（Token定价、推理成本）',
      'PM深度vs算法深度（第一层）：PM要理解Transformer"做了什么"（注意力决定模型关注什么），不需要知道Q×K^T数学推导。PM要能判断"这个任务模型能不能做"，不需要能训练模型',
      '第二层（方向PM需要）：RAG管道设计（分块策略、嵌入选型、检索质量诊断）、Agent系统设计（工具调用、规划循环、记忆管理）、评估方法论（评估集设计、Bad Case分类、指标选择）、微调决策（何时微调vs Prompt vs RAG）',
      'PM深度vs算法深度（第二层）：PM不需要写检索代码，但必须能诊断"为什么RAG返回了错误文档"。PM不需要训练模型，但必须能判断"微调能不能解决这个问题"',
      '第三层（架构PM需要）：分布式推理架构（模型服务、缓存、负载均衡）、降级策略（大模型→小模型→规则→人工）、成本优化（量化/蒸馏/模型路由的代价收益）、可靠性工程（SLO、错误预算、故障响应）',
      'PM深度vs算法深度（第三层）：PM不需要实现量化，但必须理解INT4将成本降4倍同时可能质量降2%，能决定这个权衡是否可接受',
      '验证方式：第一层—用3句话向非技术人解释LLM、写一个对比3种模型的Prompt、算一笔Token成本账；第二层—设计一个RAG评估协议（50个测试用例）、写一个Agent系统Prompt；第三层—写一个多模型降级方案、设计一个AI产品SLO看板',
    ] },
    { name: 'AI发展史与里程碑', points: [
      '1956达特茅斯会议：AI概念的诞生，约翰·麦卡锡提出"人工智能"',
      '1980s专家系统：知识驱动的AI第一次商业化浪潮',
      '1997深蓝vs卡斯帕罗夫：AI在棋类游戏中的里程碑胜利',
      '2012 AlexNet：深度学习在ImageNet上的突破，开启深度学习时代',
      '2016 AlphaGo vs李世石：强化学习的里程碑，AI在复杂策略游戏中超越人类',
      '2017 Transformer论文：注意力机制改变NLP，"Attention is All You Need"',
      '2022 ChatGPT发布：大语言模型的公众化，AI进入大众视野',
      '2024多模态大模型：GPT-4V/Gemini，AI从文本走向多模态理解',
    ] },
    { name: 'AI产业链全景', points: [
      '芯片层：NVIDIA/AMD/华为昇腾，算力是AI的基础设施',
      '云平台层：AWS/Azure/GCP/阿里云，AI训练和推理的云服务',
      '模型层：OpenAI/Anthropic/Google/Meta，基础大模型的竞争格局',
      '工具层：LangChain/LlamaIndex/Hugging Face，AI开发的工具链',
      '应用层：ChatGPT/Copilot/Midjourney，面向用户的AI产品',
      '数据层：Scale AI/Labelbox，AI训练数据的标注和管理',
      '评估层：HumanEval/MMLU/MT-Bench，AI效果的评估基准',
      '安全层：AI安全/对齐/红队测试，AI的负责任发展',
    ] },
    { name: 'AI前沿技术趋势', points: [
      '长上下文窗口：从4K到128K到1M Token，上下文长度的竞赛',
      '多模态融合：视觉+语言+音频+视频的统一理解和生成',
      'AI Agent：从对话到行动，AI自主完成复杂任务',
      '小模型+蒸馏：用大模型训练小模型，成本降低10x',
      '端侧AI：在手机/电脑上运行AI，隐私和延迟的优势',
      'AI搜索：Perplexity/SearchGPT，AI重新定义搜索',
      'AI编程：Copilot/Cursor/Devin，AI改变软件开发',
      '具身智能：AI+机器人，AI从数字世界走向物理世界',
    ] },
  ],
  'prompt-engineering': [
    { name: 'Prompt安全与防御', points: [
      'Prompt注入攻击：直接注入/间接注入/越狱攻击的原理和案例',
      '防御策略：输入过滤/指令隔离/输出校验/权限控制',
      '红队测试：主动攻击自己的AI产品，发现安全漏洞',
      '安全评估框架：OWASP LLM Top 10，AI安全的十大风险',
      '内容安全：AI生成有害内容的检测和过滤策略',
      '隐私保护：Prompt中敏感信息的检测和脱敏',
      '合规要求：不同行业对AI安全的合规要求',
      '安全运营：AI安全事件的监控、响应和复盘',
    ] },
    { name: 'Prompt优化方法论', points: [
      'DSPy框架：用编程方式自动优化Prompt，告别手工调参',
      'OPRO优化：用LLM优化LLM的Prompt，元优化方法',
      '自动Prompt生成：根据任务描述自动生成初始Prompt',
      'Prompt压缩：减少Token数量的同时保持效果',
      'Prompt组合：多个Prompt的组合策略和调度方法',
      '效果追踪：Prompt变更的效果追踪和回归测试',
      '成本优化：在效果和成本之间找到最优平衡点',
      'Prompt模板库：可复用的Prompt模板设计和管理',
    ] },
    { name: '企业级Prompt管理', points: [
      'Prompt版本管理：Git式的Prompt版本追踪和回滚',
      'Prompt审批流程：Prompt变更的审批和灰度发布',
      'Prompt监控：线上Prompt的效果监控和异常检测',
      'Prompt文档化：Prompt的设计文档、变更记录、效果报告',
      'Prompt团队协作：多人协作编辑Prompt的流程和工具',
      'Prompt知识库：团队共享的Prompt最佳实践库',
      'Prompt合规审计：Prompt的合规性检查和审计追踪',
      'Prompt成本管理：Prompt的Token成本追踪和预算控制',
    ] },
  ],
  'ai-workflow': [
    { name: 'AI工作流监控与运维', points: [
      '实时监控：工作流执行状态、延迟、错误率的实时看板',
      '告警策略：异常检测规则、告警阈值、告警升级流程',
      '日志管理：结构化日志、分布式追踪、日志检索和分析',
      '性能分析：工作流瓶颈定位、慢步骤优化、资源利用率分析',
      '容量规划：基于历史数据的容量预测和弹性伸缩策略',
      '故障恢复：工作流失败后的自动重试、断点续传、降级策略',
      '变更管理：工作流变更的灰度发布、回滚策略、影响评估',
      'SRE实践：AI工作流的SLO定义、错误预算、事故响应',
    ] },
    { name: '低代码AI应用开发', points: [
      'Dify：开源AI应用开发平台，可视化工作流编排',
      'Coze：字节跳动的AI Bot开发平台，插件生态丰富',
      'Flowise：开源的LangChain可视化工具，拖拽式开发',
      'n8n：通用自动化平台+AI节点，业务流程自动化',
      'Zapier AI：连接5000+应用的AI自动化',
      'Make(Integromat)：可视化自动化工作流+AI模块',
      'Retool AI：内部工具开发平台+AI组件',
      '选型指南：不同平台的适用场景、扩展性、成本对比',
    ] },
    { name: 'AI工作流安全与合规', points: [
      '数据安全：工作流中的数据加密、脱敏、访问控制',
      '权限管理：不同角色的操作权限和数据访问权限',
      '审计日志：工作流操作的完整审计追踪',
      '合规要求：不同行业对AI自动化的合规要求',
      '风险评估：AI自动化工作流的风险识别和评估',
      '人工审批：关键步骤的人工审批机制设计',
      '数据留存：工作流数据的留存策略和合规要求',
      '安全审计：定期的AI工作流安全审计和渗透测试',
    ] },
    { name: 'Vibe Coding开发与实战', points: [
      'Vibe Coding理念：用自然语言描述需求，AI生成代码，人负责意图和验收、AI负责实现细节，从"写代码"到"审代码"的角色转变',
      '核心工具链：Cursor（AI原生IDE+Agent模式）、Claude Code（终端AI助手+多文件编辑）、GitHub Copilot（行内补全+Chat）、Windsurf（AI流式编辑）、Cline（VS Code自主编码Agent）',
      'Cursor实战：Composer多文件编辑、Agent模式自动探索代码库、@引用上下文（文件/文档/网页）、.cursorrules项目规范、Review模式代码审查',
      'Claude Code实战：终端交互式开发、CLAUDE.md项目指令、多文件并行编辑、MCP工具扩展、/commands自定义工作流、worktree隔离开发',
      '开发模式：Spec驱动（先写规格再让AI实现）、TDD驱动（先写测试再让AI补实现）、增量迭代（小步修改逐步验证）、Agent自主（给目标让AI自主完成）',
      '代码审查与质量：AI生成代码必须人工Review、关注边界处理/错误处理/安全漏洞、建立AI代码Review Checklist、用AI辅助Review AI生成的代码',
      '项目管理：.cursorrules/CLAUDE.md项目规范文件、统一代码风格和架构约定、AI上下文管理（避免幻觉）、版本控制策略（AI修改的原子提交）',
      '进阶技巧：多Agent协作（设计Agent+编码Agent+测试Agent）、MCP协议扩展工具能力、自定义命令自动化工作流、AI辅助调试和性能优化、从原型到生产的代码质量提升路径',
    ] },
  ],
  'ai-architecture': [
    { name: '技术沟通与可行性评估', points: [
      '技术可行性评估：判断"技术能不能做、值不值得做、风险在哪"。成熟度评估、成本估算、风险识别',
      '架构图阅读：看懂系统架构图，理解数据流和调用链。识别关键组件、瓶颈点、风险点',
      '技术风险识别：预判技术方案的坑。延迟风险、成本风险、可扩展性风险、安全风险',
      '需求→技术规范转化：把业务需求翻译成工程师能执行的规格。功能规格、性能规格、安全规格',
      '与算法团队沟通：提出正确问题、理解回答、识别搪塞。效果问题怎么问、成本问题怎么问、风险问题怎么问',
      '技术决策参与：PM在技术决策中的角色。定义问题、提供业务视角、做权衡决策',
    ] },
    { name: 'AI系统可靠性设计', points: [
      '高可用架构：多区域部署、故障转移、自动恢复策略',
      '降级策略：从大模型→小模型→规则引擎→人工兜底的多层降级',
      '限流与熔断：防止流量突增导致系统崩溃的保护机制',
      '数据一致性：分布式AI系统的数据一致性保证',
      '灾备方案：模型服务不可用时的完整灾备方案',
      '混沌工程：主动注入故障测试系统韧性',
      '容量规划：基于负载预测的容量规划和弹性伸缩',
      'SLO设计：AI系统的SLO定义、错误预算和事故响应流程',
    ] },
    { name: 'AI系统性能优化', points: [
      '推理加速：模型量化(INT8/INT4)/蒸馏/剪枝的效果和成本权衡',
      '缓存策略：语义缓存/精确缓存/多级缓存的设计',
      '批处理优化：请求合并/动态批处理/优先级队列',
      '模型路由：根据请求复杂度路由到不同大小的模型',
      '流式输出：Server-Sent Events/WebSocket的流式输出实现',
      '预热策略：模型冷启动的预热和懒加载策略',
      'GPU利用率：GPU显存管理、模型并行、推理优化',
      '端到端延迟优化：从请求到响应的全链路延迟分解和优化',
    ] },
    { name: 'AI系统安全架构', points: [
      '模型安全：模型权重保护、推理API的安全设计',
      '数据安全：训练数据和推理数据的加密和脱敏',
      '网络安全：AI服务的网络隔离、API网关、DDoS防护',
      '供应链安全：模型/数据/依赖的安全审计',
      '隐私计算：联邦学习/差分隐私/安全多方计算',
      'AI水印：AI生成内容的可追溯水印技术',
      '红队测试：系统化的AI安全测试方法论',
      '安全合规：SOC2/ISO27001/GDPR对AI系统的要求',
    ] },
  ],
  'ai-commercialization': [
    { name: 'AI产品市场分析', points: [
      '市场规模估算：TAM/SAM/SOM的自上而下和自下而上方法',
      '竞争格局分析：波特五力/竞争矩阵/蓝海策略在AI市场的应用',
      '用户需求验证：AI产品的需求验证方法，避免"技术找问题"',
      '定价基准分析：AI产品市场的定价基准和差异化空间',
      '渠道分析：直销/合作伙伴/平台集成的渠道效率和成本',
      '趋势判断：Gartner Hype Cycle在AI产品中的应用',
      '地域差异：不同地区AI产品的市场差异和本地化需求',
      '行业垂直：通用AI产品vs行业垂直AI产品的市场选择',
    ] },
    { name: 'AI产品运营策略', points: [
      '用户运营：AI产品的用户生命周期管理和分层运营',
      '内容运营：AI产品的内容策略和UGC/PGC/AIGC内容体系',
      '社区运营：AI开源社区/用户社区的建设和运营',
      '品牌运营：AI产品的品牌定位和差异化传播',
      '数据运营：AI产品的数据飞轮设计和运营',
      '客户成功：企业级AI产品的客户成功体系和最佳实践',
      '增长运营：AI产品的增长实验体系和数据驱动增长',
      '危机运营：AI产品事故的危机公关和用户沟通',
    ] },
    { name: 'AI产品合规与监管', points: [
      'EU AI Act：欧盟AI法案的核心要求和对产品的影响',
      '中国AI监管：生成式AI管理办法/深度合成规定的合规要求',
      '数据合规：GDPR/个人信息保护法对AI产品的数据要求',
      '行业监管：金融/医疗/教育等行业的AI特殊监管',
      '算法备案：中国算法推荐规定的备案和审计要求',
      '内容审核：AI生成内容的审核标准和流程',
      '合规即竞争力：如何把合规转化为产品优势',
      '合规团队建设：AI产品合规团队的组织和流程',
    ] },
  ],
  'data-metrics': [
    { name: '需求分析方法论', points: [
      '需求挖掘：从模糊需求中提炼真问题。5Why追问、用户场景还原、问题vs解决方案分离',
      '需求验证：用最小成本验证需求真伪。假门测试、数据验证、用户访谈',
      '需求优先级：频率×严重度×实现成本的ROI排序。Kano模型区分基本型/期望型/兴奋型',
      '需求文档：AI PRD的特殊性。模型行为规范、边界case处理、降级方案、效果指标',
      '需求变更：AI项目需求变更频繁。变更流程、影响评估、版本管理',
      '伪需求识别：用户说想要≠真需要。行为数据验证、场景还原、动机分析',
    ] },
    { name: '竞品分析框架', points: [
      '竞品选择：直接竞品、间接竞品、潜在竞品的识别和选择',
      '功能拆解：不是功能罗列，而是逻辑和策略推演。功能→场景→用户价值→技术实现',
      '体验对比：实际使用竞品，记录体验差异。首次使用、核心流程、错误处理',
      '数据对比：公开数据、第三方数据、自己采集数据的对比分析',
      '策略推演：从竞品动作推演其战略意图。为什么做这个功能？下一步可能做什么？',
      '差异化定位：找到竞品没做好但用户需要的空间。蓝海策略、差异化竞争',
    ] },
    { name: '数据工程基础', points: [
      '数据仓库：Snowflake/BigQuery/Redshift的选型和使用',
      'ETL流程：数据抽取/转换/加载的完整流程设计',
      '数据质量：数据完整性/准确性/一致性的监控和保障',
      '数据治理：数据字典/血缘分析/元数据管理的体系',
      '实时数据：Kafka/Flink的实时数据处理管道',
      '数据安全：数据脱敏/加密/访问控制的安全策略',
      '数据成本：数据存储和计算的成本优化',
      '数据文化：建立"数据驱动决策"的团队文化',
    ] },
    { name: 'AI产品数据特殊性', points: [
      '模型效果数据：准确率/召回率/F1/延迟/吞吐量的监控体系',
      '用户反馈数据：显式(点赞/踩)/隐式(复制/编辑/放弃)反馈的收集',
      'Bad Case数据：错误分类/根因分析/改进追踪的数据体系',
      '成本数据：Token用量/推理成本/单位经济的数据追踪',
      '安全数据：安全事件/偏见检测/内容审核的数据体系',
      'A/B测试数据：实验平台/指标体系/统计显著性检验',
      '数据飞轮：用户行为→数据→模型→体验的闭环数据流',
      '数据合规：数据采集/存储/使用的合规数据体系',
    ] },
    { name: '数据可视化与叙事', points: [
      '图表选择：折线图/柱状图/散点图/热力图/漏斗图的适用场景',
      'Dashboard设计：关键指标看板的设计原则和最佳实践',
      '数据报告：从数据到洞察到行动的报告撰写方法',
      '实时看板：AI产品效果实时监控看板的设计',
      '异常告警：数据异常的自动检测和告警策略',
      '自助分析：让团队自助查询数据的工具和培训',
      '数据民主化：让每个人都能用数据做决策的文化建设',
      '数据故事：用数据讲好产品故事，影响决策者',
    ] },
  ],
  'ai-evaluation': [
    { name: 'AI评估前沿方法', points: [
      'LLM-as-Judge进阶：位置偏差/长度偏差/自我偏好的校准方法',
      '多维度评估：准确性/完整性/相关性/流畅性/安全性的多维度框架',
      '对抗评估：用对抗样本测试AI的鲁棒性和安全边界',
      '人工评估优化：标注者培训/一致性检验/主动学习选择样本',
      '自动化评估流水线：CI/CD集成的自动化评估，每次变更都跑评测',
      '评估数据集构建：高质量评估数据集的构建和维护方法',
      '跨模型评估：同一评测在不同模型上的对比和基准',
      '评估成本优化：在评估质量和成本之间找到最优平衡',
    ] },
    { name: 'AI效果优化闭环', points: [
      '评估→分析→优化：从评估发现问题到优化解决的完整闭环',
      'Bad Case驱动优化：从Bad Case中发现系统性问题并优先修复',
      'A/B测试驱动优化：用实验验证优化效果，避免主观判断',
      '数据驱动优化：用数据发现优化方向，用数据验证优化效果',
      '用户反馈驱动优化：从用户反馈中发现优化机会',
      '成本效果平衡：在效果提升和成本增加之间找到最优解',
      '优化优先级：频率×严重度×修复成本的ROI排序',
      '优化节奏：小步快跑vs大步跨越的优化策略选择',
    ] },
    { name: 'AI评估工具生态', points: [
      'Promptfoo：开源的Prompt评估和测试框架',
      'LangSmith：LangChain的评估和可观测性平台',
      'Weights & Biases Weave：ML实验追踪和评估',
      'Arize AI：ML模型监控和评估平台',
      'Braintrust：AI产品的评估和迭代平台',
      'Ragas：RAG系统的自动化评估框架',
      'TruLens：LLM应用的质量评估框架',
      '评估工具选型：不同工具的适用场景和成本对比',
    ] },
  ],
  'product-strategy': [
    { name: 'AI产品组合战略', points: [
      '产品矩阵规划：现金牛/明星/问题/瘦狗的BCG矩阵应用',
      '平台化战略：从AI工具到AI平台到AI生态的演进路径',
      '能力复用：AI能力在多个产品间的复用和平台化',
      '第二曲线：在第一曲线还在增长时启动第二曲线',
      '产品线扩展：从单品到产品线的扩展策略和节奏',
      '技术债管理：何时还债vs何时前行，债务的量化',
      '资源分配：ROI驱动的投资组合优化',
      '退出策略：产品退出的时机判断和用户迁移方案',
    ] },
    { name: 'AI竞争情报', points: [
      '竞品监控：AI竞品的功能/定价/技术路线的持续监控',
      '专利分析：AI领域的专利布局和技术趋势分析',
      '论文追踪：关键AI论文的追踪和技术趋势判断',
      '人才流动：AI人才市场的流动趋势和薪酬水平',
      '融资动态：AI创业公司的融资动态和估值变化',
      '开源生态：AI开源项目的发展趋势和生态竞争',
      '政策法规：AI监管政策的变化和影响分析',
      '竞争预警：建立AI竞争情报的预警机制',
    ] },
    { name: 'AI产品国际化战略', points: [
      '出海时机：AI产品出海的最佳时机判断',
      '市场选择：不同国家AI市场的机会和挑战分析',
      '本地化策略：AI产品的本地化不只是翻译，还有模型和内容适配',
      '合规挑战：不同国家AI监管对产品出海的影响',
      '文化适配：不同文化背景下AI产品的交互和内容差异',
      '支付本地化：不同国家的支付习惯和定价策略',
      '渠道本地化：不同国家的获客渠道和营销策略',
      '团队本地化：海外团队的组建和管理策略',
    ] },
  ],
  'ai-leadership': [
    { name: 'AI产品组织设计', points: [
      'AI团队结构：中心化/去中心化/混合式AI团队的组织设计',
      'AI CoE：AI卓越中心的组织定位和职能设计',
      '跨职能协作：PM+工程师+研究员+设计师的最优协作模式',
      'AI人才招聘：AI PM/工程师/研究员的招聘标准和面试方法',
      'AI人才培养：内部AI人才培养体系和晋升路径设计',
      'AI文化塑造：实验文化/数据文化/安全文化的建设方法',
      '远程AI团队：AI团队的远程协作最佳实践',
      'AI团队绩效：AI团队的绩效评估和激励机制设计',
    ] },
    { name: 'AI产品创新管理', points: [
      '创新流程：从创意到验证到规模化AI产品的创新流程设计',
      '创新指标：AI产品创新的度量指标和评估方法',
      '创新预算：AI创新项目的预算分配和ROI评估',
      '快速验证：AI产品创意的快速验证方法和工具',
      '失败管理：AI创新项目失败的处理和知识沉淀',
      '创新文化：在大型组织中建立AI创新文化的方法',
      '开放创新：与高校/创业公司/开源社区的合作创新',
      '创新治理：AI创新的合规审查和风险管理',
    ] },
    { name: 'AI产品危机管理', points: [
      'AI事故分类：模型事故/数据事故/安全事故/合规事故',
      '危机预案：AI产品事故的应急预案和响应流程',
      '危机沟通：AI事故的对内对外沟通策略',
      '根因分析：AI事故的5-Why分析和系统性改进',
      '用户补偿：AI事故对用户影响的评估和补偿方案',
      '监管应对：AI事故的监管报告和合规应对',
      '品牌修复：AI事故后的品牌信任修复策略',
      '预防体系：从"救火"到"防火"的AI安全预防体系',
    ] },
  ],
  'job-preparation': [
    { name: 'AI PM面试全流程解析', points: [
      'HR初筛：简历关键词匹配+基本条件筛选，通过率约20%',
      '业务一面：场景题+项目深挖，考察AI场景判断力和产品思维',
      '业务二面：技术理解+效果评估，考察AI技术深度和评估能力',
      '交叉面：跨团队面试官，考察协作能力和文化匹配',
      '技术面：和算法工程师面试，考察技术沟通能力',
      'CEO/VP面：战略思维+价值观，考察长期潜力和判断力',
      '每轮重点不同：需要针对不同轮次准备不同的故事和案例',
      '面试节奏：通常2-4周完成全部流程，保持状态和节奏',
    ] },
    { name: 'AI PM作品集准备', points: [
      '作品集结构：项目案例+产品分析+技术理解+个人洞察',
      'AI项目案例：完整的AI产品方案，从PRD到评估到迭代',
      '产品分析报告：对3-5个AI产品的深度分析，展示洞察力',
      '技术理解展示：用通俗语言解释AI技术，展示理解深度',
      '个人博客/文章：AI相关的技术写作，展示思考深度',
      '开源贡献：参与AI开源项目的记录，展示技术热情',
      '数据可视化：用数据讲AI产品故事的能力展示',
      '作品集平台：Notion/GitHub Pages/个人网站的选择和搭建',
    ] },
    { name: 'AI PM职业发展规划', points: [
      '1年规划：补齐AI基础知识，完成1-2个AI项目，建立AI PM认知',
      '3年规划：成为独立负责AI产品的PM，建立行业影响力',
      '5年规划：成为AI产品领域的专家，带团队或创业',
      '技能树规划：硬技能/软技能/行业知识的3年技能树',
      '人脉规划：AI社区/行业会议/导师关系的建设',
      '品牌规划：技术写作/公开演讲/社交媒体的个人品牌建设',
      '转型规划：从传统PM到AI PM的6个月转型路线图',
      '持续学习：AI领域变化快，终身学习是必须而非选择',
    ] },
  ],
  'conversational-ai': [
    { name: '对话流设计进阶', points: [
      '对话状态管理：有限状态机(FSM)建模、状态转移条件设计、异常状态恢复',
      '多轮对话管理：上下文窗口管理、对话历史压缩、话题切换与回溯',
      '槽位填充设计：必填/可选槽位、槽位依赖关系、多值槽位、槽位确认策略',
      '意图识别体系：显式意图/隐式意图/复合意图的识别和处理策略',
      '对话评估：任务完成率/对话轮数/转人工率/用户满意度的评估体系',
    ] },
    { name: '知识库运营', points: [
      '知识库架构：FAQ/文档/结构化知识的多层知识库设计',
      '知识更新机制：新增/修改/失效知识的自动检测和更新流程',
      '知识质量评估：覆盖度/准确度/时效性的量化评估',
      'RAG增强知识库：向量检索+知识图谱的混合知识库架构',
    ] },
    { name: '人机协作对话设计', points: [
      '转人工策略：基于意图/情绪/复杂度的智能转人工判断',
      '坐席辅助：AI实时建议/知识推荐/话术生成的坐席辅助系统',
      '降本增效路径：从全人工到AI辅助到AI为主到全自动的渐进路径',
      '用户预期管理：AI能力边界沟通、避免过度承诺、渐进式能力展示',
    ] },
  ],
  'learning-resources': [
    { name: '学习路径推荐', points: [
      '产品优先路径：产品思维→用户研究→AI基础→产品设计→商业化→战略',
      '技术优先路径：AI基础→Prompt→RAG→Agent→评估→架构',
      '均衡发展路径：产品+AI双线并进，每阶段产品+技术结合学习',
    ] },
  ],
  'ai-requirement-spec': [
    { name: 'AI需求拆解实践', points: [
      '需求拆解模板：功能需求/模型需求/数据需求/评测需求四维度拆解',
      '模型规格书：输入输出定义/能力边界/性能指标/安全约束',
      '验收标准设计：分级标准/Bad Case容忍度/验收门禁',
      'AI PRD模板：标准结构+模型行为规范+降级方案+上线Checklist',
    ] },
  ],
  'rag-architecture': [
    { name: 'RAG架构设计实践', points: [
      'Naive RAG到Advanced RAG：从简单检索到混合检索+重排序的演进',
      'Agentic RAG：Agent自主决定何时检索、检索什么、如何整合',
      'RAG评测体系：RAGAS/TruLens自动化评测、检索准确率/回答忠实度',
      'RAG产品设计：企业知识库/智能客服/文档问答的RAG方案设计',
    ] },
  ],
  'ai-agent-design': [
    { name: 'Agent设计实践', points: [
      'Agent架构选型：ReAct/Plan-and-Execute/Reflexion的适用场景',
      '工具调用设计：Function Calling/MCP协议/工具选择策略',
      '多Agent协作：分工策略/通信协议/冲突解决/AutoGen/CrewAI',
      'Agent评测：任务完成率/工具调用准确率/规划合理性评估',
    ] },
  ],
  'cn-llm-ecosystem': [
    { name: '国产模型选型实践', points: [
      '模型对比：文心/通义/智谱/Kimi/DeepSeek的能力和成本对比',
      'API生态：OpenAI兼容格式/SDK成熟度/定价对比',
      '私有化部署：开源模型选择/硬件需求/运维成本评估',
      '选型决策：评测集设计/POC验证/成本效益分析',
    ] },
  ],
  'ai-vendor-evaluation': [
    { name: '供应商评估实践', points: [
      '评估框架：能力/成本/稳定性/生态/合规五维评估',
      'POC验证：评测集设计/通过标准/时间规划',
      '成本分析：TCO计算/ROI预估/隐性成本识别',
      '风险评估：供应商锁定/技术路线/合规/迁移风险',
    ] },
  ],
  'data-quality-annotation': [
    { name: '数据标注管理实践', points: [
      '标注规范设计：定义/示例/边界Case/常见错误四部分',
      '质量管控：抽检策略/一致性指标(Kappa)/标注员培训',
      '数据飞轮：用户反馈→自动标注→主动学习→效果提升闭环',
      'Bad Case管理：分类/归因/修复优先级/回归验证',
    ] },
  ],
  'badcase-analysis': [
    { name: 'Bad Case分析实践', points: [
      '分类体系：幻觉/偏题/安全/格式/一致性/逻辑错误',
      '归因分析：数据/模型/Prompt/系统四维归因+5-Why深度追问',
      '回归测试集：核心场景+历史Bad Case的测试集维护',
      '效果追踪：核心指标看板/趋势分析/异常告警/效果归因',
    ] },
  ],
  'hitl-design': [
    { name: '人机协同设计实践', points: [
      '人机分工策略：任务分类/置信度阈值/动态调整/分级处理',
      '审核流程设计：审核队列/审核界面/效率指标/审核员管理',
      '渐进式自动化：全人工→AI辅助→AI为主→全自动的四阶段路径',
      '实战案例：内容审核/智能客服/AI写作/数据分析的HITL设计',
    ] },
  ],
  'content-compliance': [
    { name: '内容合规实践', points: [
      '合规框架：生成式AI管理办法/算法推荐规定/数据安全法/个人信息保护法',
      '审核策略：前置过滤/实时审核/后置复审/用户举报多层体系',
      '敏感词体系：分类管理/动态更新/模糊匹配/对抗检测',
      '合规评审：评审节点/评审清单/风险分级/整改流程',
    ] },
  ],
  'ai-growth': [
    { name: 'AI 产品增长黑客', points: [
      '病毒循环设计：用户创造内容→其他用户看到→注册使用→创造更多内容',
      '增长实验模板：假设→最小实验→数据验证→规模化推广的四步法',
      'AI产品特有增长手段：能力更新通告/模型效果提升推送/新功能预告',
      '社区驱动增长：用户分享Prompt/模板/工作流，UGC成为增长引擎',
    ] },
    { name: '企业级 AI 产品增长', points: [
      'PLG vs SLG：产品驱动增长vs销售驱动增长在AI产品中的选择',
      'Enterprise特征：长决策链/多角色/POC驱动/年度预算周期',
      '从0到1的企业客户获取：标杆客户/行业案例/生态合作',
      '从1到N的规模化：标准化交付/自助化onboarding/合作伙伴体系',
    ] },
  ],
  'ai-safety': [
    { name: 'AI 安全评估体系', points: [
      '安全评估框架：OWASP LLM Top 10的风险清单和评估方法',
      '红队测试流程：自动化+人工红队测试的组合策略',
      '安全指标：拒绝率/误拒率/越狱成功率/信息泄露率的监控',
      '安全审计：定期安全审计的流程和标准',
    ] },
    { name: '负责任AI实践', points: [
      'AI伦理框架：公平性/透明性/可解释性/隐私保护/问责制',
      '影响评估：AI系统上线前的影响评估(AI Impact Assessment)',
      '可解释性：LIME/SHAP等模型解释方法在产品中的应用',
      'AI治理：组织内部的AI治理结构和决策流程',
    ] },
  ],
  'data-flywheel': [
    { name: '数据飞轮加速策略', points: [
      '飞轮启动器：免费增值/社区贡献/爬取公开数据/合成数据',
      '飞轮加速器：主动学习/自动标注/弱监督学习/数据增强',
      '飞轮维护：数据质量监控/标注规范更新/模型效果回归测试',
      '飞轮度量：标注效率/模型提升幅度/用户满意度变化/数据覆盖度',
    ] },
    { name: '合成数据与数据增强', points: [
      'LLM生成合成数据：用GPT-4生成训练数据/测试数据/评估数据',
      '数据增强策略：同义改写/回译/扰动/风格迁移',
      '合成数据的局限：分布偏差/多样性不足/隐私风险',
      '合成+真实混合：合成数据预训练+真实数据微调的分层策略',
    ] },
  ],
  'ai-frontier': [
    { name: 'AI Agent 生态前沿', points: [
      'Computer Use：Claude/OpenAI的计算机操作能力，AI直接操控浏览器和桌面应用',
      'MCP生态发展：MCP Server市场/企业级MCP部署/MCP安全认证',
      'Agent基础设施：记忆系统/工具市场/评估框架/监控平台',
      '多模态Agent：视觉+语音+文本的多模态Agent设计模式',
    ] },
    { name: 'AI 产品形态演进', points: [
      '从Chatbot到Agent：对话式→工具调用→自主规划→多Agent协作',
      '从Copilot到Autopilot：人机协作→人机协同→AI自主→人机共生',
      '从SaaS到AIaaS：软件即服务→AI能力即服务的商业模式变革',
      '从工具到伙伴：AI产品从工具定位向智能助手/数字员工演进',
    ] },
  ],
  'job-practice': [
    { name: 'AI PM 面试项目框架', points: [
      'AI产品分析模板：产品定位→技术架构→用户价值→商业模式→竞争壁垒',
      'AI产品改进提案：发现痛点→提出方案→技术可行性→预期效果→实施路径',
      'AI产品从0到1设计：场景选择→用户定义→核心交互→技术选型→指标设计',
      '现场白板框架：5分钟理解→10分钟框架→10分钟细化→5分钟总结',
    ] },
    { name: 'AI PM 求职材料', points: [
      'AI PM简历模板：项目经历用AI Context(技术栈+模型+效果)量化',
      'AI PM求职信：展示对AI产品的理解和思考深度',
      'AI PM作品集网站：用Next.js/Framer搭建个人作品集',
      '技术博客选题：AI产品分析/技术解读/行业观察/实战经验',
    ] },
  ],
};

export const EXTRA_CASES: Record<string, { title: string; company: string; lesson: string }[]> = {
  'pm-thinking': [
    { title: '微信的克制哲学', company: '微信', lesson: '张小龙"用完即走"的产品哲学，克制比堆功能更难，少即是多的极致实践' },
    { title: 'Amazon的Working Backwards', company: 'Amazon', lesson: '从新闻稿开始倒推产品，先定义成功再设计方案，逆向思维的制度化' },
    { title: '字节跳动的A/B测试文化', company: '字节跳动', lesson: '所有产品决策都靠A/B测试，数据驱动到极致，但也要警惕数据短视' },
  ],
  'user-research': [
    { title: '微信的朋友圈调研', company: '微信', lesson: '张小龙说"我不用调研因为用户不知道自己想要什么"，但微信团队做了大量行为数据分析' },
    { title: 'Apple的用户研究秘密', company: 'Apple', lesson: 'Apple不做焦点小组，而是深度观察用户行为，发现用户自己都没意识到的需求' },
    { title: 'Netflix的个性化实验', company: 'Netflix', lesson: '用A/B测试决定封面图，不同用户看到不同封面，点击率提升30%' },
  ],
  'product-design': [
    { title: 'Siri的信任危机', company: 'Apple', lesson: '早期Siri过度承诺导致信任崩塌，AI产品必须管理用户预期，宁可保守也不要过度承诺' },
    { title: 'Replika的情感设计', company: 'Replika', lesson: 'AI伴侣产品的情感设计，如何让用户和AI建立情感连接，同时保持伦理边界' },
    { title: 'Character.AI的角色设计', company: 'Character.AI', lesson: 'AI角色的个性设计，不同角色满足不同需求，从教育到娱乐到情感陪伴' },
  ],
  'pm-capability': [
    { title: '从运营到AI PM的转型', company: '某互联网公司', lesson: '运营PM通过系统学习AI+做内部AI项目，6个月成功转型，关键是有AI项目实战经验' },
    { title: '技术背景PM的优势', company: '某AI创业公司', lesson: '计算机背景的PM和算法团队沟通效率高3倍，但需要补业务理解能力' },
    { title: 'AI PM的日常一天', company: '某大厂AI团队', lesson: '上午看数据/Bad Case，下午和算法对方案，晚上写PRD，AI PM是数据+技术+产品的桥梁' },
  ],
  'ai-fundamentals': [
    { title: 'AlphaFold的突破', company: 'DeepMind', lesson: 'AI解决蛋白质折叠问题，从科学难题到AI突破，展示了AI在科学领域的巨大潜力' },
    { title: 'DALL-E的创意能力', company: 'OpenAI', lesson: '从文本到图像的生成，AI的创意能力边界在哪里，版权和伦理的挑战' },
    { title: 'Stable Diffusion的开源影响', company: 'Stability AI', lesson: '开源模型如何改变AI生态，从封闭到开放的力量' },
  ],
  'prompt-engineering': [
    { title: 'AutoGPT的兴起与局限', company: '开源社区', lesson: '自主Agent的早期尝试，展示了可能性也暴露了可靠性问题' },
    { title: 'ChatGPT的Prompt迭代', company: 'OpenAI', lesson: '从GPT-3到ChatGPT，Prompt设计和RLHF如何让产品体验天差地别' },
    { title: 'Wolfram Alpha+ChatGPT', company: 'OpenAI+Wolfram', lesson: '工具调用让AI从"只会说话"到"能做计算"，RAG和工具的结合' },
  ],
  'ai-workflow': [
    { title: 'Zapier的AI自动化', company: 'Zapier', lesson: '从规则自动化到AI自动化，5000+应用的AI集成工作流' },
    { title: 'Shopify的AI客服', company: 'Shopify', lesson: 'AI客服处理80%的常见问题，复杂问题无缝转人工，人机协作的标杆' },
    { title: 'Bloomberg的金融AI工作流', company: 'Bloomberg', lesson: '金融数据的AI处理工作流，从数据采集到分析到报告的全自动化' },
  ],
  'ai-architecture': [
    { title: 'Cloudflare的AI推理网络', company: 'Cloudflare', lesson: '边缘计算+AI推理，全球分布式的AI推理架构，延迟降低10x' },
    { title: 'Uber的ML平台Michelangelo', company: 'Uber', lesson: '大规模ML系统的平台化实践，从模型训练到部署到监控的完整平台' },
    { title: 'Pinterest的推荐架构', company: 'Pinterest', lesson: '从规则到ML到深度学习的推荐系统演进，架构选择的技术决策' },
  ],
  'ai-commercialization': [
    { title: 'Hugging Face的商业模式', company: 'Hugging Face', lesson: '从开源社区到商业化的路径，开源模型+企业服务的双轮驱动' },
    { title: 'Jasper的兴衰', company: 'Jasper', lesson: 'AI写作工具的先发优势和后来者的挑战，产品差异化比先发更重要' },
    { title: 'Scale AI的数据飞轮', company: 'Scale AI', lesson: '数据标注→模型训练→效果提升→更多客户→更多数据的飞轮' },
  ],
  'data-metrics': [
    { title: 'Facebook的增长团队', company: 'Facebook/Meta', lesson: '数据驱动增长的鼻祖，从"7天加10好友"的北极星指标到增长飞轮' },
    { title: 'Airbnb的数据文化', company: 'Airbnb', lesson: '每个决策都有数据支撑，数据民主化让每个人都能用数据做决策' },
    { title: '字节跳动数据中台', company: '字节跳动', lesson: '数据中台支撑全公司数据驱动决策，从数据采集到分析到决策的闭环' },
  ],
  'ai-evaluation': [
    { title: 'Tesla的自动驾驶评估', company: 'Tesla', lesson: '从模拟测试到影子模式到真实路测的多层评估体系，AI安全的极致实践' },
    { title: 'Google搜索的AI评估', company: 'Google', lesson: '搜索质量评估的黄金标准，人工评估+自动化评估+在线实验的三层体系' },
    { title: 'Anthropic的Constitutional AI评估', company: 'Anthropic', lesson: '用AI评估AI的安全性和对齐程度，自动化安全评估的创新方法' },
  ],
  'product-strategy': [
    { title: 'Google的AI优先战略', company: 'Google', lesson: '从Mobile First到AI First的战略转型，组织和文化先行，技术跟进' },
    { title: 'Meta的AI投入', company: 'Meta', lesson: '开源Llama模型的战略考量，从封闭到开放，生态竞争的新范式' },
    { title: '百度All in AI', company: '百度', lesson: '中国最早All in AI的大厂，先发优势vs执行力的教训' },
  ],
  'ai-leadership': [
    { title: 'Sam Altman的领导力', company: 'OpenAI', lesson: '从Y Combinator到OpenAI，技术判断力+商业直觉+使命驱动的领导力' },
    { title: 'Dario Amodei的安全优先', company: 'Anthropic', lesson: '从OpenAI分裂到创立Anthropic，AI安全优先的领导力选择' },
    { title: '李飞飞的AI民主化', company: 'Stanford', lesson: 'ImageNet的创建者，推动AI民主化和负责任AI发展的学术领导力' },
  ],
  'job-preparation': [
    { title: '从零到AI PM offer', company: '社区案例', lesson: '非技术背景，3个月自学AI+做项目+面试准备，拿到3个AI PM offer' },
    { title: '大厂AI PM面试全记录', company: '某大厂', lesson: '5轮面试的完整记录，每轮的题目、回答和复盘，最真实的面试参考' },
    { title: 'AI PM的薪资谈判实录', company: '社区案例', lesson: '从初始offer到最终package，每一步的谈判策略和结果' },
  ],
  'conversational-ai': [
    { title: '小冰的情感对话引擎', company: '小冰', lesson: 'EQ优先的对话设计，情感连接比任务完成更能留住用户' },
    { title: '阿里小蜜的双11实战', company: '阿里巴巴', lesson: '对话系统在极端流量下的稳定性设计，智能转人工策略应对突发峰值' },
    { title: 'Intercom的客服机器人', company: 'Intercom', lesson: '从FAQ机器人到全栈客服平台的演进，人机协作的渐进式自动化路径' },
  ],
  'learning-resources': [
    { title: 'Andrew Ng的AI课程生态', company: 'DeepLearning.AI', lesson: '从Coursera入门到专项课程体系，系统化学习路径比碎片化学习效率高3倍' },
    { title: 'Hugging Face的模型实战', company: 'Hugging Face', lesson: '从模型库到Spaces到课程，边做边学比纯看课程效果更好' },
  ],
  'ai-requirement-spec': [
    { title: '某大厂AI搜索PRD实战', company: '某大厂', lesson: 'AI搜索需求的四维拆解：功能需求/模型需求/数据需求/评测需求缺一不可' },
    { title: '智能客服需求翻车案例', company: '某金融公司', lesson: '需求只写了"回答用户问题"，没有定义能力边界和降级方案，上线后Bad Case率40%' },
  ],
  'rag-architecture': [
    { title: 'Notion AI的知识检索', company: 'Notion', lesson: '个人知识库的RAG实践，语义检索+结构化元数据的混合方案效果最佳' },
    { title: '某银行智能问答RAG', company: '某银行', lesson: '金融RAG的核心挑战：准确率要求99%+，必须加验证层和兜底机制' },
    { title: 'Perplexity的实时RAG', company: 'Perplexity', lesson: '实时网页检索+AI总结的RAG架构，检索质量决定回答质量的上限' },
  ],
  'ai-agent-design': [
    { title: 'Devin的自主编程Agent', company: 'Cognition', lesson: '自主Agent的天花板在于规划能力，复杂任务分解是核心瓶颈' },
    { title: 'AutoGPT的兴衰启示', company: '开源社区', lesson: 'Agent不是万能的——没有明确目标和约束的自主Agent只会无限循环' },
    { title: 'Cursor的编码Agent', company: 'Cursor', lesson: '实用Agent设计：人在回路中做关键决策，Agent负责执行，效率提升5x' },
  ],
  'cn-llm-ecosystem': [
    { title: 'DeepSeek的逆袭', company: 'DeepSeek', lesson: '开源模型性能逼近GPT-4，中国AI的开源路线可以弯道超车' },
    { title: 'Kimi的长上下文突破', company: '月之暗面', lesson: '200万字上下文窗口的产品化，长文本是中文场景的差异化竞争力' },
    { title: '文心一言的企业化路径', company: '百度', lesson: '从通用模型到行业模型的落地，企业级场景需要领域定制而非通用能力' },
  ],
  'ai-vendor-evaluation': [
    { title: '某银行AI供应商切换', company: '某银行', lesson: '从OpenAI切换到国产模型，TCO降低60%但需要3个月迁移和效果对齐' },
    { title: '某SaaS公司的多供应商策略', company: '某SaaS公司', lesson: '不绑定单一供应商，用模型路由根据任务复杂度选择最优模型，成本降40%' },
  ],
  'data-quality-annotation': [
    { title: 'Scale AI的标注平台', company: 'Scale AI', lesson: '标注质量=标注员培训+质检体系+工具支持，三者缺一不可' },
    { title: '某自动驾驶标注项目', company: '某自动驾驶公司', lesson: '2D标注→3D标注→4D标注的复杂度跳跃，标注成本占项目总成本30%' },
    { title: 'ChatGPT的RLHF标注', company: 'OpenAI', lesson: '人类偏好标注是RLHF的核心，标注员选择和培训直接影响模型对齐质量' },
  ],
  'badcase-analysis': [
    { title: '某搜索AI的Bad Case治理', company: '某搜索引擎', lesson: '建立Bad Case分类体系后，修复效率提升3倍——先分类再归因再修复' },
    { title: '某客服机器人的幻觉治理', company: '某电商平台', lesson: '幻觉类Bad Case占60%，根因是知识库覆盖不足+模型过度推理，双管齐下解决' },
  ],
  'hitl-design': [
    { title: 'Tesla自动驾驶的人机协同', company: 'Tesla', lesson: '渐进式自动化的典范：从辅助驾驶到FSD，每一步都保留人类接管能力' },
    { title: '医疗AI的诊断辅助', company: '某医疗AI公司', lesson: 'AI给建议、医生做决策，人机协同在医疗场景的核心是"辅助"而非"替代"' },
    { title: '内容审核的人机分工', company: '某社交平台', lesson: 'AI过滤95%的明确违规，人工处理5%的灰色地带，效率和质量的最优平衡' },
  ],
  'content-compliance': [
    { title: '某AIGC平台的合规整改', company: '某AIGC平台', lesson: '算法备案+内容审核+数据合规三座大山，合规不是成本而是准入门槛' },
    { title: 'TikTok的内容审核体系', company: '字节跳动', lesson: '全球化的内容合规挑战：不同国家不同法规，本地化审核团队+AI审核的组合方案' },
  ],
  'ai-growth': [
    { title: 'Perplexity的病毒式增长', company: 'Perplexity', lesson: '产品即增长引擎——AI搜索体验远超传统搜索，用户自发传播' },
    { title: 'Cursor的社区驱动增长', company: 'Cursor', lesson: '开发者社区+KOL推荐+产品效果自证，零广告费的AI工具增长范式' },
  ],
  'ai-safety': [
    { title: 'ChatGPT的越狱攻防战', company: 'OpenAI', lesson: '攻防持续升级——每个防御策略都会被新攻击绕过，安全是持续过程不是一次性工程' },
    { title: 'Google Gemini的偏见事件', company: 'Google', lesson: '过度对齐导致种族/性别偏见矫枉过正，安全与有用性的平衡非常微妙' },
  ],
  'data-flywheel': [
    { title: 'Duolingo的数据飞轮', company: 'Duolingo', lesson: '5亿用户的练习数据→个性化学习模型→更好的学习效果→更多用户，教育AI的飞轮样本' },
    { title: 'Copilot的代码补全飞轮', company: 'GitHub', lesson: '开发者接受/拒绝补全→模型学习代码模式→补全更准确→开发者更依赖' },
  ],
  'ai-frontier': [
    { title: 'MCP生态爆发', company: 'Anthropic', lesson: '开放协议+开发者社区=生态爆发，MCP Server数量3个月增长10倍' },
    { title: 'Claude Computer Use', company: 'Anthropic', lesson: 'AI从对话到操作的跨越——Computer Use让AI能操控任何桌面应用' },
  ],
  'job-practice': [
    { title: '从零作品集到AI PM Offer', company: '某AI创业公司', lesson: '3周搭建2个AI Demo+1篇产品分析→面试时直接演示→3个Offer' },
    { title: '传统PM的AI转型', company: '某大厂', lesson: '6个月系统学习AI+输出技术博客+内部转岗，成功从电商PM转型AI PM' },
  ],
};

export const EXTRA_MUSTREAD: Record<string, { title: string; author: string; why: string }[]> = {
  'pm-thinking': [
    { title: '《俞军产品方法论》', author: '俞军', why: '中国产品经理的必读，产品价值=（新体验-旧体验）-替换成本' },
    { title: '《第二曲线创新》', author: '李善友', why: '在第一曲线还在增长时启动第二曲线，AI时代的创新思维' },
  ],
  'user-research': [
    { title: '《设计心理学》', author: 'Don Norman', why: '理解用户心理和行为的经典，交互设计的理论基础' },
    { title: '《Don\'t Make Me Think》', author: 'Steve Krug', why: '可用性设计的入门经典，简单直接的方法论' },
  ],
  'product-design': [
    { title: '《The Design of Everyday Things》', author: 'Don Norman', why: '设计思维的经典，理解好设计和坏设计的本质' },
    { title: '《About Face：交互设计精髓》', author: 'Alan Cooper', why: '交互设计的圣经，目标导向设计方法论' },
  ],
  'pm-capability': [
    { title: '《人人都是产品经理》', author: '苏杰', why: '中国PM入门经典，产品经理的基本功和思维方式' },
    { title: '《产品经理面试实战》', author: '多个作者', why: 'PM面试的实战指南，含AI PM面试的特殊准备' },
  ],
  'ai-fundamentals': [
    { title: '《Life 3.0》', author: 'Max Tegmark', why: 'AI对人类未来的影响，从技术到哲学的深度思考' },
    { title: '《The Book of Why》', author: 'Judea Pearl', why: '因果推断的入门，理解"为什么"比"是什么"更重要' },
  ],
  'prompt-engineering': [
    { title: '《Prompt Engineering for Generative AI》', author: 'James Phoenix', why: 'Prompt工程的系统化教材，从基础到高级' },
    { title: 'Anthropic: Prompt Engineering文档', author: 'Anthropic', why: 'Claude的官方Prompt指南，和OpenAI的方法互补' },
  ],
  'ai-workflow': [
    { title: '《Fundamentals of Data Engineering》', author: 'Joe Reis', why: '数据工程基础，AI工作流的数据管道设计' },
    { title: '《Building Event-Driven Microservices》', author: 'Adam Bellemare', why: '事件驱动架构，AI工作流的异步处理设计' },
  ],
  'ai-architecture': [
    { title: '《Understanding Distributed Systems》', author: 'Roberto Vitillo', why: '分布式系统入门，AI系统的底层架构基础' },
    { title: '《System Design Interview Vol.2》', author: 'Alex Xu', why: '系统设计面试进阶，更多架构模式和权衡' },
  ],
  'ai-commercialization': [
    { title: '《Crossing the Chasm》', author: 'Geoffrey Moore', why: '跨越鸿沟的经典，AI产品从早期采用者到大众市场的策略' },
    { title: '《The Lean Startup》', author: 'Eric Ries', why: '精益创业方法论，AI产品商业化的快速验证方法' },
  ],
  'data-metrics': [
    { title: '《Storytelling with Data》', author: 'Cole Nussbaumer Knaflic', why: '用数据讲故事的实战指南，让数据洞察影响决策' },
    { title: '《Naked Statistics》', author: 'Charles Wheelan', why: '统计学的通俗入门，理解数据背后的统计原理' },
  ],
  'ai-evaluation': [
    { title: '《Evaluating Machine Learning Models》', author: 'Alicia Loh', why: 'ML模型评估的实战指南，从离线到线上的评估方法' },
    { title: 'OWASP LLM Top 10', author: 'OWASP', why: 'AI安全的十大风险清单，评估AI产品安全性的框架' },
  ],
  'product-strategy': [
    { title: '《The Innovator\'s Solution》', author: 'Clayton Christensen', why: '创新者的解决方案，如何在颠覆中找到机会' },
    { title: '《Competitive Strategy》', author: 'Michael Porter', why: '竞争战略的经典，五力模型和竞争策略的理论基础' },
  ],
  'ai-leadership': [
    { title: '《The Five Dysfunctions of a Team》', author: 'Patrick Lencioni', why: '团队建设的经典，识别和解决团队问题的框架' },
    { title: '《Radical Candor》', author: 'Kim Scott', why: '直接关怀的反馈方法，AI团队高效沟通的基础' },
  ],
  'job-preparation': [
    { title: '《What Color Is Your Parachute》', author: 'Richard Bolles', why: '职业规划的经典，找到最适合你的职业方向' },
    { title: 'AI PM面试题库（GitHub）', author: '社区整理', why: '最全的AI PM面试题库，持续更新的社区资源' },
  ],
  'conversational-ai': [
    { title: '《Designing Bots》', author: 'Amir Shevat', why: '对话式产品设计的实战指南，从用户需求到对话流的完整方法论' },
    { title: '《Conversational AI》', author: 'Michael McTear', why: '对话AI的技术与设计，理解对话系统从NLU到DM到NLG的全链路' },
  ],
  'learning-resources': [
    { title: 'DeepLearning.AI课程体系', author: 'Andrew Ng', why: '从AI入门到专项领域最系统的课程路径，适合PM补充技术基础' },
    { title: 'Anthropic官方文档', author: 'Anthropic', why: 'Claude模型的最佳实践和Prompt指南，一线厂商的工程经验' },
  ],
  'ai-requirement-spec': [
    { title: '《AI产品经理手册》', author: '多位作者', why: 'AI需求拆解和PRD写作的实战参考，含模型规格书和验收标准模板' },
    { title: 'Google PAIR Guide', author: 'Google PAIR', why: 'AI产品设计的指南，从需求定义到公平性评估的系统方法' },
  ],
  'rag-architecture': [
    { title: '《Building LLM Apps》', author: 'Valentina Alto', why: 'LLM应用开发实战，含RAG架构设计的完整案例' },
    { title: 'LlamaIndex官方文档', author: 'LlamaIndex', why: 'RAG框架的最佳实践，从索引构建到检索优化到评估的完整指南' },
  ],
  'ai-agent-design': [
    { title: '《Multi-Agent Systems》', author: 'Yoav Shoham', why: '多Agent系统的理论基础，理解Agent协作和博弈的学术视角' },
    { title: 'LangGraph官方文档', author: 'LangChain', why: 'Agent工作流编排的工程实践，ReAct和Plan-and-Execute的实现指南' },
  ],
  'cn-llm-ecosystem': [
    { title: '《大模型时代》', author: '龙志勇', why: '中国大模型产业的全景分析，从技术到商业到政策的系统梳理' },
    { title: '智谱AI技术博客', author: '智谱AI', why: '国产模型的技术解读和应用案例，理解GLM系列的技术路线' },
  ],
  'ai-vendor-evaluation': [
    { title: 'Gartner AI供应商评估报告', author: 'Gartner', why: '权威的AI供应商评估框架和排名，选型决策的重要参考' },
    { title: '《Vendor Risk Management》', author: 'Norman Marks', why: '供应商风险管理的系统方法，AI供应商的特殊风险识别' },
  ],
  'data-quality-annotation': [
    { title: '《Data Quality for ML》', author: 'Elena Suvorova', why: 'ML数据质量的实战指南，从标注规范到质检体系到数据飞轮' },
    { title: 'Scale AI最佳实践文档', author: 'Scale AI', why: '数据标注行业的标杆实践，标注员培训和质检流程的参考' },
  ],
  'badcase-analysis': [
    { title: 'Google SRE第11章', author: 'Google SRE Team', why: '故障分析的工程方法论，Bad Case分析可借鉴的系统化排查思路' },
    { title: '《Thinking in Bets》', author: 'Annie Duke', why: '不确定条件下的决策思维，Bad Case归因需要避免后见之明偏差' },
  ],
  'hitl-design': [
    { title: '《Human-in-the-Loop Machine Learning》', author: 'Robert Monarch', why: 'HITL的实战指南，从主动学习到标注管理到人机协作设计' },
    { title: 'Apple的差分隐私设计', author: 'Apple', why: '隐私保护下的人机协同设计，如何在收集反馈的同时保护用户隐私' },
  ],
  'content-compliance': [
    { title: '《生成式AI管理办法》解读', author: '多位法律专家', why: '中国AI合规的核心法规，理解监管红线和合规要求' },
    { title: 'Stanford HAI年度AI指数', author: 'Stanford HAI', why: '全球AI政策和发展趋势的年度报告，合规趋势的风向标' },
  ],
  'ai-growth': [
    { title: '《Lean Analytics》', author: 'Alistair Croll', why: '数据驱动增长的方法论，选择正确的指标比增长速度更重要' },
    { title: 'a16z: The New Business of AI', author: 'a16z', why: 'AI商业模式和增长策略的深度分析' },
  ],
  'ai-safety': [
    { title: 'Anthropic: Core Views on AI Safety', author: 'Anthropic', why: 'AI安全公司的一手安全理念，理解前沿安全思考' },
    { title: 'OWASP Top 10 for LLM', author: 'OWASP', why: 'AI应用安全风险的权威清单' },
  ],
  'data-flywheel': [
    { title: 'Data Flywheel: The Secret Behind Great AI Products', author: 'a16z', why: '理解AI产品数据飞轮的核心文章' },
    { title: '《Building ML Powered Applications》', author: 'Emmanuel Ameisen', why: '从数据到产品的完整闭环实践' },
  ],
  'ai-frontier': [
    { title: 'State of AI Report', author: 'Nathan Benaich', why: '年度AI行业全景报告，技术趋势和投资方向' },
    { title: 'The Architecture of Open Source Applications(AI篇)', author: '开源社区', why: '理解主流AI开源项目的架构设计' },
  ],
  'job-practice': [
    { title: 'Cracking the PM Interview', author: 'Gayle McDowell', why: 'PM面试方法论经典，AI PM同样适用' },
    { title: 'The Product Book', author: 'Product School', why: '产品经理的完整知识体系，面试基础' },
  ],
};

export const EXTRA_INTERVIEWQS: Record<string, { question: string; hint: string }[]> = {
  'pm-thinking': [
    { question: '如何处理产品方向和老板意见不一致的情况？', hint: '用数据说话，做小实验验证，给老板选择而非反对，展示专业判断力' },
    { question: '你如何判断一个产品功能是否应该下线？', hint: '从使用率/用户价值/维护成本/替代方案四个维度评估，数据驱动决策' },
  ],
  'user-research': [
    { question: '用户说想要的功能和实际使用的行为不一致，你怎么办？', hint: '行为比言语更真实，用行为数据验证，但也要理解"想要"背后的需求' },
    { question: '如何用最小成本验证一个用户需求？', hint: 'Guerrilla研究/假门测试/数据验证，5个用户就能发现85%的问题' },
  ],
  'product-design': [
    { question: 'AI产品的"个性化"和"一致性"如何平衡？', hint: '核心体验一致，个性化在边缘，用户应该能预期AI的行为' },
    { question: '如何设计AI产品的"撤销"功能？', hint: '不是简单的Ctrl+Z，而是AI行为的回退、调整和覆盖能力' },
  ],
  'pm-capability': [
    { question: '你最近学的一个AI概念是什么？用通俗语言解释', hint: '展示持续学习的习惯，用类比解释复杂概念的能力' },
    { question: 'AI PM最重要的三个能力是什么？为什么？', hint: 'AI技术理解/效果评估/场景判断，每个都用例子说明' },
  ],
  'ai-fundamentals': [
    { question: 'Transformer为什么比RNN更适合处理长文本？', hint: '并行计算+全局注意力vs序列计算+局部依赖，效率和能力双重优势' },
    { question: '什么是AI的涌现能力？为什么重要？', hint: '小模型做不到但大模型可以的能力，量变到质变，对产品设计的启示' },
  ],
  'prompt-engineering': [
    { question: '如何设计一个多轮对话的Prompt方案？', hint: '系统Prompt+上下文管理+意图追踪+工具调用，每一步的设计要点' },
    { question: 'Prompt效果不稳定怎么办？', hint: '温度参数/采样策略/多次采样取多数/结构化输出，稳定性优化方法' },
  ],
  'ai-workflow': [
    { question: '如何设计一个容错的AI工作流？', hint: '重试/降级/跳过/人工介入的多层错误处理，幂等性设计' },
    { question: 'AI工作流和传统软件工作流最大的区别是什么？', hint: '不确定性——AI输出不可预测，需要更多的错误处理和人工审批节点' },
  ],
  'ai-architecture': [
    { question: '如何设计AI系统的降级方案？', hint: '大模型→小模型→规则引擎→人工兜底，每层的触发条件和用户体验' },
    { question: 'AI系统的成本如何优化？', hint: '缓存/量化/模型路由/批处理/蒸馏，不同方法的成本降低比例和效果影响' },
  ],
  'ai-commercialization': [
    { question: 'AI产品免费层和付费层的边界怎么划？', hint: '核心体验免费+增值收费，用量/功能/效果三个维度的边界设计' },
    { question: 'AI产品的定价如何应对模型成本波动？', hint: '成本传导机制/缓存优化/模型路由/长期合同，多策略组合' },
  ],
  'data-metrics': [
    { question: '如何为一个AI产品定义北极星指标？', hint: '反映用户核心价值/可衡量/可操作/领先指标，AI产品的特殊性' },
    { question: 'A/B测试结果和用户反馈矛盾怎么办？', hint: '深挖矛盾原因——指标选择/样本偏差/长期vs短期，不要简单选一个' },
  ],
  'ai-evaluation': [
    { question: '如何设计一个AI产品的评估体系？', hint: '自动评测+人工评测+线上监控+安全评估的四层框架' },
    { question: 'LLM-as-Judge有什么局限？如何弥补？', hint: '位置偏差/长度偏差/自我偏好，用校准和混合方法弥补' },
  ],
  'product-strategy': [
    { question: 'AI产品的护城河是什么？', hint: '数据飞轮/网络效应/转换成本/生态锁定，不同阶段不同护城河' },
    { question: '如何判断AI产品的市场时机？', hint: '技术成熟度/用户接受度/竞争格局/监管环境的综合判断' },
  ],
  'ai-leadership': [
    { question: '如何管理一个AI产品的不确定性？', hint: '小步快跑/快速验证/数据驱动/预留缓冲，不确定性是AI产品的常态' },
    { question: 'AI团队和传统产品团队的管理有什么不同？', hint: '实验文化/技术沟通/效果评估/安全意识，AI团队的特殊管理需求' },
  ],
  'job-preparation': [
    { question: '你为什么想做AI PM而不是传统PM？', hint: '展示对AI的热情和理解，但不贬低传统PM，强调AI PM的独特价值' },
    { question: '你如何保持AI知识的更新？', hint: '具体的学习习惯：关注的技术博客/论文/社区，每周的学习时间' },
  ],
  'conversational-ai': [
    { question: '对话机器人的转人工率多少合适？怎么优化？', hint: '行业基准20-30%，按意图分类看——简单意图<5%，复杂意图>60%，优化要分场景' },
    { question: '多轮对话中用户突然换话题怎么处理？', hint: '话题检测+上下文保留+确认意图，不要直接丢弃之前对话的状态' },
  ],
  'learning-resources': [
    { question: '你推荐一个AI PM的3个月学习计划？', hint: '第1月AI基础+Prompt，第2月RAG+评估，第3月项目实战，每周10小时' },
  ],
  'ai-requirement-spec': [
    { question: 'AI需求的"模型规格书"应该包含哪些内容？', hint: '输入输出定义/能力边界/性能指标/安全约束/Bad Case容忍度，比传统PRD多了模型行为规范' },
    { question: '如何定义AI功能的验收标准？', hint: '分级标准（必须达到/建议达到/可接受）+Bad Case容忍度+验收门禁（多少测试用例通过才可上线）' },
  ],
  'rag-architecture': [
    { question: 'RAG检索质量不好怎么排查？', hint: '分步骤诊断：分块策略→Embedding质量→检索策略→重排序→生成质量，逐层定位' },
    { question: '什么时候用RAG，什么时候用微调？', hint: '知识更新频繁用RAG，行为模式改变用微调，两者可以组合使用' },
  ],
  'ai-agent-design': [
    { question: 'Agent陷入循环怎么办？', hint: '设置最大步数限制+重复检测+强制终止+人工介入，Agent必须有退出机制' },
    { question: '多Agent系统如何避免冲突？', hint: '明确分工+中央协调+冲突检测+优先级排序，避免两个Agent做同一件事' },
  ],
  'cn-llm-ecosystem': [
    { question: '国产模型和GPT-4的主要差距在哪？', hint: '复杂推理/长文本理解/代码生成/多语言能力有差距，但中文场景差距缩小，成本优势明显' },
    { question: '私有化部署国产模型的核心考量？', hint: '硬件成本/推理性能/运维复杂度/效果损失/安全合规，不是所有场景都适合私有化' },
  ],
  'ai-vendor-evaluation': [
    { question: '如何评估AI供应商的长期稳定性？', hint: '融资情况/客户案例/技术路线/团队稳定性/合规资质，不要只看当前效果' },
    { question: '供应商锁定风险怎么规避？', hint: '抽象层设计/OpenAI兼容格式/多供应商备份/定期切换演练，降低迁移成本' },
  ],
  'data-quality-annotation': [
    { question: '标注一致性Kappa值低于0.7怎么办？', hint: '标注规范不够清晰/边界Case定义模糊/标注员培训不足，从规范和培训入手而非换人' },
    { question: '如何用AI辅助标注提升效率？', hint: '预标注+人工校验/主动学习选样本/半自动标注工具，效率提升3-5倍' },
  ],
  'badcase-analysis': [
    { question: 'Bad Case数量太多，怎么优先处理？', hint: '频率×严重度×修复成本的ROI排序，先修高频+严重+低成本的Quick Win' },
    { question: '如何区分模型问题和Prompt问题？', hint: '同一个Bad Case用不同Prompt测试，换模型交叉验证，隔离变量定位根因' },
  ],
  'hitl-design': [
    { question: '人机协同的置信度阈值怎么定？', hint: '根据错误代价设定——高代价任务阈值高（如医疗90%+），低代价任务阈值低（如推荐60%）' },
    { question: '如何设计渐进式自动化路线图？', hint: '从全人工开始→AI辅助→AI为主→全自动，每个阶段都有明确的升级指标和回退机制' },
  ],
  'content-compliance': [
    { question: 'AI生成内容的版权归属怎么处理？', hint: '目前法律尚不明确，建议在用户协议中约定，声明AI生成内容的版权归属和使用限制' },
    { question: '算法备案需要准备什么？', hint: '算法基本原理/数据来源/使用场景/安全评估/应急处置，建议提前3个月准备' },
  ],
  'ai-growth': [
    { question: 'AI产品的免费额度应该怎么设计？', hint: '够用但不够爽——让用户充分体验价值，但高级功能需要付费解锁' },
    { question: '如何衡量AI产品的增长质量？', hint: '不只看DAU，看使用深度(功能覆盖度/Prompt复杂度/模型调用量)' },
  ],
  'ai-safety': [
    { question: '如何设计AI产品的安全测试方案？', hint: '分层测试：单元测试(输入验证)+集成测试(端到端安全)+红队测试(对抗攻击)' },
    { question: '模型对齐过度会有什么问题？', hint: '过度拒绝合法请求(over-refusal)、创造力下降、用户体验变差——安全与有用性的平衡' },
  ],
  'data-flywheel': [
    { question: '如何判断数据飞轮是否在正常运转？', hint: '看三个指标：用户反馈量是否增长、模型效果是否持续提升、用户留存是否改善' },
    { question: '合成数据能替代真实用户数据吗？', hint: '不能完全替代——合成数据适合预训练和测试，真实数据对微调和效果验证不可替代' },
  ],
  'ai-frontier': [
    { question: 'AutoGen和CrewAI的核心区别是什么？', hint: 'AutoGen侧重多Agent对话协作(适合研究)，CrewAI侧重角色驱动的任务编排(适合生产)' },
    { question: 'MCP对AI产品生态意味着什么？', hint: '类似USB-C统一接口——让AI应用能即插即用任何工具，降低集成成本，加速生态发展' },
  ],
  'job-practice': [
    { question: '你如何证明自己适合AI PM而非传统PM？', hint: '展示AI技术理解+AI产品思维+数据驱动决策能力，用具体项目案例说话' },
    { question: 'AI PM面试中最常见的坑是什么？', hint: '只谈技术不谈产品——面试官想看的是你如何用AI解决用户问题，而非你对模型的理解深度' },
  ],
};

export const EXTRA_PITFALLS: Record<string, string[]> = {
  'pm-thinking': ['不要把产品失败归咎于市场——先反思自己的判断和决策过程', '不要忽视产品的"反脆弱"设计——好的产品应该能从错误中学习'],
  'user-research': ['不要在研究方案设计阶段就预设结论——确认偏差是最常见的陷阱', '不要忽视定量和定性的结合——单一方法都有盲区'],
  'product-design': ['不要把AI的"智能"当作理所当然——用户需要看到AI在思考', '不要忽略AI产品的"冷启动"体验——第一次使用决定了用户是否留下'],
  'pm-capability': ['不要把AI PM当作"懂AI的PM"——AI PM是"用AI解决问题的PM"', '不要忽视行业知识——AI技术+行业洞察才是真正的竞争力'],
  'ai-fundamentals': ['不要把AI当作万能解决方案——很多问题用规则引擎就够了', '不要忽视AI的能耗问题——大模型的碳足迹和可持续性是真实挑战'],
  'prompt-engineering': ['不要忽视Prompt的可维护性——复杂的Prompt比代码更难维护和测试', '不要把所有业务逻辑都放进Prompt——该写代码就写代码'],
  'ai-workflow': ['不要忽视工作流的文档化——没有文档的工作流是定时炸弹', '不要追求100%自动化——有些步骤人工介入比AI更高效更可靠'],
  'ai-architecture': ['不要忽视AI系统的可调试性——出了问题你都不知道哪一步错了', '不要把AI系统的架构和传统软件架构等同——AI系统有独特的挑战'],
  'ai-commercialization': ['不要忽视AI产品的"边际成本"——每多一个用户的推理成本是真实存在的', '不要把AI产品的商业化想得太简单——技术好≠产品好≠能赚钱'],
  'data-metrics': ['不要忽视数据质量——脏数据比没有数据更危险', '不要把数据当作客观真理——数据收集和分析都有主观性'],
  'ai-evaluation': ['不要只评估"好"的情况——AI在边缘case的表现才是真正的质量指标', '不要把评估当作一次性项目——持续评估才是正确姿势'],
  'product-strategy': ['不要忽视AI的"民主化"趋势——技术壁垒在降低，护城河需要重新定义', '不要把战略想得太复杂——好的战略应该一句话能说清楚'],
  'ai-leadership': ['不要忽视一线工程师的声音——最好的洞察往往来自离代码最近的人', '不要用KPI管理AI团队——实验文化需要容错空间'],
  'job-preparation': ['不要海投简历——精准投递+内推的效果是海投的10倍', '不要在面试中贬低前公司——展示成长而非抱怨'],
  'conversational-ai': ['不要把对话机器人设计成万能的——越聚焦的机器人体验越好', '不要忽视对话的"温度"——冷冰冰的回复会让用户立刻流失', '不要跳过异常对话的测试——用户说"我不明白"时的回复比正常回复更重要'],
  'learning-resources': ['不要贪多求全——选一条学习路径坚持3个月比收藏100个课程有效', '不要只看视频不动手——AI学习必须动手实践，看10小时课程不如做1小时项目'],
  'ai-requirement-spec': ['不要在PRD中只写"AI智能回答"——必须定义能力边界、降级方案和验收标准', '不要忽略模型需求的文档化——模型规格书和功能PRD同样重要'],
  'rag-architecture': ['不要忽视检索质量——RAG的效果上限由检索质量决定，生成只是锦上添花', '不要用单一检索策略——混合检索（关键词+语义）比任何单一策略都好'],
  'ai-agent-design': ['不要让Agent拥有不受限的行动能力——每一步都需要验证和约束', '不要低估Agent的调试难度——Agent的不可预测性比传统软件高一个数量级'],
  'cn-llm-ecosystem': ['不要盲目追求国产替代——先评估场景适配度，有些场景国产模型确实还有差距', '不要忽视国产模型的API生态成熟度——SDK文档/社区/工单响应差异很大'],
  'ai-vendor-evaluation': ['不要只看评测分数跑分——实际业务场景的POC验证比任何榜单都可靠', '不要忽视隐性成本——迁移成本/学习成本/运维成本可能占总成本40%'],
  'data-quality-annotation': ['不要低估标注规范的重要性——模糊的规范会导致30%以上的标注返工', '不要用众包做专业领域标注——医疗/法律/金融需要领域专家标注'],
  'badcase-analysis': ['不要只分析单个Bad Case——找到模式比修单个Case更重要', '不要忽视Good Case的监控——效果退化可能从Good Case变Borderline开始'],
  'hitl-design': ['不要追求100%自动化——有些场景人工介入比AI更可靠更高效', '不要忽视审核员体验——审核界面效率提升10%等于整体吞吐量提升10%'],
  'content-compliance': ['不要把合规当作上线后才做的事——合规要从产品设计阶段就嵌入', '不要忽视用户举报的信号——用户举报是内容合规的最后一道防线也是最重要的反馈源'],
  'ai-growth': ['不要用烧钱补贴换增长——AI产品的增长核心靠效果和口碑', '不要只看拉新不看留存——AI产品的LTV来自长期使用深度，不是一次性体验'],
  'ai-safety': ['不要以为部署了内容审核就安全了——Prompt注入可以绕过任何内容审核', '不要把安全当作阻碍——好的安全设计可以成为产品卖点(隐私保护/安全承诺)'],
  'data-flywheel': ['不要忽视反馈噪声——10条高质量反馈比1000条点赞更有价值', '不要只采集不行动——用户反馈如果不转化为产品改进，用户会停止反馈'],
  'ai-frontier': ['不要追每个热点——80%的AI热点会在6个月内降温，关注有落地场景的技术', '不要只看论文不看工程——从论文到产品的距离比你想象的大得多'],
  'job-practice': ['不要只刷面试题——作品集和项目经验比题海更有效', '不要海投简历——AI PM岗位少而精，精准投递+内推比海投成功率高5倍'],
};

export const EXTRA_KEYQUESTIONS: Record<string, string[]> = {
  'pm-thinking': ['你的产品决策有多少是数据驱动的？有多少是直觉驱动的？比例对吗？', '如果让你重新做一次这个产品，你会做什么不同的决策？'],
  'user-research': ['你的用户研究结论上次改变产品决策是什么时候？', '你最近一次发现"用户行为和预期不一致"是什么时候？你怎么处理的？'],
  'product-design': ['你的AI产品第一次使用体验是什么？用户3秒内能理解AI在做什么吗？', 'AI出错时你的产品体验是什么？用户有控制感吗？'],
  'pm-capability': ['你最近学的一个AI概念是什么？能用通俗语言解释吗？', '你的AI PM能力自检得分是多少？最短板是什么？'],
  'ai-fundamentals': ['你能用3句话解释Transformer的注意力机制吗？', 'AI的涌现能力对你的产品设计有什么影响？'],
  'prompt-engineering': ['你的Prompt有回归测试吗？修改后怎么确保不破坏已有效果？', '你的Prompt方案在换模型后还能用吗？兼容性如何？'],
  'ai-workflow': ['你的AI工作流出错率是多少？出错后的恢复时间是多少？', '你的AI工作流有文档吗？新人能看懂吗？'],
  'ai-architecture': ['你的AI系统宕机过吗？恢复时间是多少？有灾备方案吗？', '你的AI系统成本趋势是什么？3个月后成本会怎样？'],
  'ai-commercialization': ['你的AI产品单位经济模型是正的吗？什么时候能盈利？', '你的AI产品免费用户到付费用户的转化路径是什么？转化率多少？'],
  'data-metrics': ['你的北极星指标上次更新是什么时候？还适用吗？', '你最近一次从数据中发现意外洞察是什么时候？'],
  'ai-evaluation': ['你的AI产品上次Bad Case分析是什么时候？发现了什么？', '你的线上效果和离线评测一致吗？如果不一致，为什么？'],
  'product-strategy': ['你的AI产品3年后的护城河是什么？', '如果大厂明天做同样的产品，你怎么防守？'],
  'ai-leadership': ['你的AI团队有实验文化吗？还是只有执行文化？', '你最近一次在AI伦理问题上做决策是什么时候？'],
  'job-preparation': ['你的AI PM简历5秒内能让人理解你做什么吗？', '你有3个完整的AI项目故事可以讲吗？每个3分钟？'],
  'conversational-ai': ['你的对话机器人转人工率是多少？哪个意图转人工率最高？', '你的对话系统上次更新知识库是什么时候？覆盖度评估过吗？'],
  'learning-resources': ['你的AI学习路径是什么？执行到哪一步了？', '你最近从哪个学习资源中获得了可以直接用在项目里的知识？'],
  'ai-requirement-spec': ['你的AI PRD有模型规格书吗？模型的行为边界定义清楚了吗？', '你的AI功能验收标准是什么？Bad Case容忍度是多少？'],
  'rag-architecture': ['你的RAG系统检索准确率是多少？上次诊断检索质量是什么时候？', '你的RAG系统用了什么分块策略？试过其他策略对比吗？'],
  'ai-agent-design': ['你的Agent最长执行过多少步？有步数限制和超时机制吗？', '你的Agent工具调用成功率是多少？哪个工具最容易失败？'],
  'cn-llm-ecosystem': ['你用过哪些国产模型？和GPT-4的差距体感如何？', '你的产品用了国产模型后效果降了多少？成本降了多少？ROI划算吗？'],
  'ai-vendor-evaluation': ['你的AI供应商切换过吗？迁移成本有多大？', '你有没有供应商锁定的风险？如果供应商明天涨价50%怎么办？'],
  'data-quality-annotation': ['你的标注一致性Kappa值是多少？上次标注规范更新是什么时候？', '你的数据飞轮转起来了吗？用户反馈到标注改进的周期多长？'],
  'badcase-analysis': ['你的Bad Case分类体系有几种类型？哪种最多？', '你最近修复的Top 3 Bad Case是什么？修复后回归测试过了吗？'],
  'hitl-design': ['你的人机协同置信度阈值是多少？怎么定的？', '你的渐进式自动化走到哪一步了？下一步的升级指标是什么？'],
  'content-compliance': ['你的产品做了算法备案吗？备案花了多长时间？', '你的内容审核拦截率和误拦率分别是多少？'],
  'ai-growth': ['你的AI产品增长飞轮转起来了吗？哪个环节最薄弱？', '免费用户和付费用户的核心行为差异是什么？'],
  'ai-safety': ['你的AI产品最可能被如何攻击？防御措施是什么？', '你的安全测试覆盖率是多少？上次红队测试是什么时候？'],
  'data-flywheel': ['用户反馈到产品改进的周期多长？能缩短吗？', '你的标注数据质量如何衡量？上次标注规范更新是什么时候？'],
  'ai-frontier': ['你每天花多少时间跟踪AI前沿？信息源有哪些？', '你最近关注的一个AI技术趋势是什么？它离产品化还有多远？'],
  'job-practice': ['你的AI PM作品集里有几个可交互的Demo？', '你最近一次AI产品分析的输出是什么？在哪里可以看到？'],
};

export const EXTRA_LEARNINGTIPS: Record<string, string[]> = {
  'pm-thinking': ['找一个你做过的产品决策，用贝叶斯更新的方式重新分析', '练习"预 mortem"：假设你的产品已经失败了，倒推可能的原因'],
  'user-research': ['用Hotjar录屏观察3个真实用户使用你的产品，记录意外行为', '设计一份5个问题的极简问卷，验证一个你不确定的用户假设'],
  'product-design': ['用Figma设计一个AI产品的错误处理流程，覆盖所有失败场景', '找一个AI产品，画出它的信任度设计方案（可解释性/置信度/控制感）'],
  'pm-capability': ['做一个AI PM能力自检表，硬技能和软技能各评1-5分', '选一个你熟悉的业务场景，设计一个AI改造方案（PRD+评估指标）'],
  'ai-fundamentals': ['在Hugging Face上试3个不同类型的模型，感受它们的能力和边界', '读一篇Transformer论文的摘要和结论，用通俗语言写一段总结'],
  'prompt-engineering': ['用Promptfoo搭建一个Prompt回归测试套件', '为同一个任务设计3种不同的Prompt策略，对比效果差异'],
  'ai-workflow': ['用Dify搭建一个简单的AI工作流，体验可视化编排', '画一个你熟悉的AI自动化流程图，标注每个步骤的错误处理策略'],
  'ai-architecture': ['画一个你熟悉的AI产品的架构图，标注每个组件的选型和原因', '设计一个AI系统的降级方案：大模型→小模型→规则→人工'],
  'ai-commercialization': ['为你熟悉的AI产品画一个商业模式画布', '对比3个AI产品的定价策略，找出差异化因素'],
  'data-metrics': ['为你正在做的产品定义一个完整的指标体系（北极星+拆解+护栏）', '练习用数据讲故事：选一个数据洞察，用1分钟讲给不同受众'],
  'ai-evaluation': ['收集50个Bad Case，尝试分类和根因分析', '设计一个LLM-as-Judge的评测方案，测试它的偏差'],
  'product-strategy': ['选一个AI赛道，做完整的市场分析（TAM+竞争+趋势）', '为你熟悉的产品画一个商业模式画布和竞争策略'],
  'ai-leadership': ['在团队内推行一个AI最佳实践，从一个小项目开始', '写一篇关于AI产品管理的深度文章，建立你的观点'],
  'job-preparation': ['整理一份AI PM常见面试题清单，每题写一个回答框架', '找3个朋友做模拟面试，录音复盘，每次迭代回答'],
  'conversational-ai': ['画一个你熟悉的对话产品的对话状态机图，标注异常状态和恢复路径', '设计一个转人工策略：定义3个触发条件、转人工话术、坐席接手流程'],
  'learning-resources': ['制定一个3个月AI学习计划，每周10小时，第1月基础/第2月进阶/第3月实战', '选一个AI课程，边学边做笔记，学完后用费曼技巧给朋友讲一遍'],
  'ai-requirement-spec': ['用四维拆解法（功能/模型/数据/评测）拆解一个你熟悉的AI功能需求', '写一份模型规格书：定义输入输出/能力边界/性能指标/Bad Case容忍度'],
  'rag-architecture': ['用LlamaIndex搭建一个最小RAG系统，用Ragas评测检索和生成质量', '对比3种分块策略（固定长度/语义分块/递归分块）在相同文档上的检索效果'],
  'ai-agent-design': ['用LangGraph实现一个ReAct Agent，设置步数限制和超时机制', '设计一个多Agent协作方案：定义3个Agent的分工、通信协议和冲突解决规则'],
  'cn-llm-ecosystem': ['注册3个国产模型API（DeepSeek/通义/智谱），用相同Prompt对比输出质量', '算一笔账：同样100万Token，国产模型和GPT-4的成本差多少？效果差多少？'],
  'ai-vendor-evaluation': ['用五维评估框架（能力/成本/稳定性/生态/合规）评估2个AI供应商', '设计一个POC验证方案：定义评测集、通过标准、时间规划、成本预算'],
  'data-quality-annotation': ['写一份标注规范：定义+示例+边界Case+常见错误，找2个人试标看一致性', '设计一个数据飞轮：用户反馈→自动标注→主动学习→效果提升的闭环流程'],
  'badcase-analysis': ['收集30个Bad Case，按6类分类（幻觉/偏题/安全/格式/一致性/逻辑），找出Top 3模式', '对一个Bad Case做5-Why归因分析，区分是数据问题、模型问题还是Prompt问题'],
  'hitl-design': ['画一个你熟悉的AI产品的人机分工矩阵：按任务类型和置信度划分人机职责', '设计一个渐进式自动化路线图：定义4个阶段、每阶段的升级指标和回退机制'],
  'content-compliance': ['梳理你的产品需要遵守的AI相关法规清单，标注每条的合规状态', '设计一个多层审核策略：前置过滤+实时审核+后置复审+用户举报，定义每层的规则'],
  'ai-growth': ['画一个你熟悉的AI产品的增长飞轮图，标注每个环节的转化率', '设计一个AI产品的免费额度方案：定义免费/付费边界和转化策略'],
  'ai-safety': ['用OWASP LLM Top 10为你的AI产品做一次安全评估', '设计一个Prompt注入防御方案：输入过滤+权限隔离+输出校验的三层防御'],
  'data-flywheel': ['画一个你熟悉的AI产品的数据飞轮图，标注数据流向和反馈闭环', '设计一个用户反馈采集方案：显式+隐式反馈各3种，评估采集成本和质量'],
  'ai-frontier': ['订阅3个AI技术Newsletter，坚持每天花15分钟快速扫描', '用CrewAI或AutoGen搭建一个简单的多Agent协作demo，体验框架差异'],
  'job-practice': ['花一周时间搭建一个AI产品Demo，作为作品集的第一个项目', '写一篇AI产品分析文章发布到知乎或Medium，练习结构化表达'],
};
